// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEJ6MzJVqQG1dgpajUTda0ttECcDgNeig',
    appId: '1:541696251868:web:8b27b7e274e171488ea119',
    messagingSenderId: '541696251868',
    projectId: 'conecta-calculadora',
    authDomain: 'conecta-calculadora.firebaseapp.com',
    storageBucket: 'conecta-calculadora.appspot.com',
    measurementId: 'G-G8G1T3T9FS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcCzd7yExpnI-JmWs0h5NwsRoIeEicD38',
    appId: '1:541696251868:android:164e4a42f124dcb38ea119',
    messagingSenderId: '541696251868',
    projectId: 'conecta-calculadora',
    storageBucket: 'conecta-calculadora.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkVP4AN-IwQ-quZqrub_nuQ1Im_B6W_tQ',
    appId: '1:541696251868:ios:5a0080036c086a9d8ea119',
    messagingSenderId: '541696251868',
    projectId: 'conecta-calculadora',
    storageBucket: 'conecta-calculadora.appspot.com',
    iosBundleId: 'com.example.counterCredit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkVP4AN-IwQ-quZqrub_nuQ1Im_B6W_tQ',
    appId: '1:541696251868:ios:5a0080036c086a9d8ea119',
    messagingSenderId: '541696251868',
    projectId: 'conecta-calculadora',
    storageBucket: 'conecta-calculadora.appspot.com',
    iosBundleId: 'com.example.counterCredit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEJ6MzJVqQG1dgpajUTda0ttECcDgNeig',
    appId: '1:541696251868:web:b5d76f6d958663aa8ea119',
    messagingSenderId: '541696251868',
    projectId: 'conecta-calculadora',
    authDomain: 'conecta-calculadora.firebaseapp.com',
    storageBucket: 'conecta-calculadora.appspot.com',
    measurementId: 'G-WQJC55VHLX',
  );
}
